/**
* OpenAPI Petstore
* This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
* 
* Values: PLACED,APPROVED,DELIVERED
*/
enum class OuterEnum(val value: kotlin.String){


    @Json(name = "placed")
    PLACED("placed"),


    @Json(name = "approved")
    APPROVED("approved"),


    @Json(name = "delivered")
    DELIVERED("delivered");


}

